export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const TOGGLE_LOGIN_PAGE = 'TOGGLE_LOGIN_PAGE'

export const DISPLAY_ALERT = ' DISPLAY_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const UPLOAD_FILE_BEGIN = ' UPLOAD_FILE_BEGIN'
export const UPLOAD_FILE_SUCCESS = ' UPLOAD_FILE_SUCCESS'
export const UPLOAD_FILE_ERROR = ' UPLOAD_FILE_ERROR'

export const ADD_VIDEO_BEGIN = ' ADD_VIDEO_BEGIN'
export const ADD_VIDEO_SUCCESS = ' ADD_VIDEO_SUCCESS'
export const ADD_VIDEO_ERROR = ' ADD_VIDEO_ERROR'

export const LOGOUT_USER = 'LOGOUT_USER'

export const GET_VIDEOS_BEGIN = 'GET_VIDEOS_BEGIN'
export const GET_VIDEOS_SUCCESS = 'GET_VIDEOS_SUCCESS'
export const GET_VIDEOS_ERROR = 'GET_VIDEOS_ERROR'

export const GET_VIDEO_BEGIN = 'GET_VIDEO_BEGIN'
export const GET_VIDEO_SUCCESS = 'GET_VIDEO_SUCCESS'
export const GET_VIDEO_ERROR = 'GET_VIDEO_ERROR'

export const FIND_AUTHOR_BEGIN = 'FIND_AUTHOR_BEGIN'
export const FIND_AUTHOR_SUCCESS = 'FIND_AUTHOR_SUCCESS'
export const FIND_AUTHOR_ERROR = 'FIND_AUTHOR_ERROR'

export const FIND_USER_BEGIN = 'FIND_USER_BEGIN'
export const FIND_USER_SUCCESS = 'FIND_USER_SUCCESS'
export const FIND_USER_ERROR = 'FIND_USER_ERROR'

export const FOLLOW_USER_BEGIN = 'FOLLOW_USER_BEGIN'
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS'
export const FOLLOW_USER_ERROR = 'FOLLOW_USER_ERROR'

export const UNFOLLOW_USER_BEGIN = 'UNFOLLOW_USER_BEGIN'
export const UNFOLLOW_USER_SUCCESS = 'UNFOLLOW_USER_SUCCESS'
export const UNFOLLOW_USER_ERROR = 'UNFOLLOW_USER_ERROR'

// export const DISPLAY_VIDEO = 'DISPLAY_VIDEO'

